# yaml file for configuration of the model
DEVICE: "cuda"
BATCH_SIZE: 2048
EPOCHS: 3
LEARNING_RATE: 0.001

MODEL: "TimeSeriesModel"
MODEL_MODE: Deep_Learning

Deep_Learning:
- "Linear"
- "TimeSeriesModel"

Machine_Learning:
- "XgbOptuna"
- "RandomForestRegressorOptuna"

Linear:
  input_size: 43
  output_size: 1
  hidden_size: 64
  dropout: 0.3

TimeSeriesModel:
  static_input_dim: 42
  hidden_dim: 1024
  output_dim: 1

XgbOptuna:
  num_boost_round: 5
  early_stopping_rounds: 3 
  n_trials: 3 

RandomForestRegressorOptuna:
  n_trials: 3
